[workspace]
resolver = "2"
members = [
    "crates/types",
    "crates/metrics",
    "crates/proto",
    "crates/tls",
    "crates/meta",
    "crates/testkit",
    "crates/chunk",
    "crates/chunkworker",
    "crates/ufs",
    "crates/client",
    "crates/fuse",
    "crates/metamaster",
    "crates/fluxfs",
]
default-members = ["crates/fluxfs"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/gongxun0928/FluxFS"

[workspace.dependencies]
anyhow = "1.0"
blake3 = "1.8"
clap = { version = "4.6", features = ["derive"] }
foyer = "0.22"
fuser = "0.18"
heed = "0.22"
opendal = { version = "0.58", features = ["services-fs", "services-s3"] }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
proptest = "1.11"
fail = "0.5"
prost = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
thiserror = "2"
uuid = { version = "1", features = ["v4", "serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util", "net", "sync", "time"] }
tonic = { version = "0.14", features = ["transport", "tls-ring", "tls-connect-info"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
fluxfs-types = { path = "crates/types" }
fluxfs-metrics = { path = "crates/metrics" }
fluxfs-proto = { path = "crates/proto" }
fluxfs-tls = { path = "crates/tls" }
fluxfs-meta = { path = "crates/meta" }
fluxfs-testkit = { path = "crates/testkit" }
fluxfs-chunk = { path = "crates/chunk" }
fluxfs-chunkworker = { path = "crates/chunkworker" }
fluxfs-ufs = { path = "crates/ufs" }
fluxfs-client = { path = "crates/client" }
fluxfs-fuse = { path = "crates/fuse" }
